# Generated by Django 4.2.4 on 2023-11-22 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_customer_wallet_bal'),
        ('SHOPPER', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.product'),
        ),
    ]
