# Generated by Django 4.2.4 on 2023-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_alter_category_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
