# Generated by Django 4.2.6 on 2023-11-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_customer_wallet_bal'),
        ('APP1', '0006_alter_category_image_alter_product_image'),
    ]

    operations = [
    ]
